// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: control/core/v1/core.proto

package core_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CoreClient is the client API for Core service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreClient interface {
	SubscribeRequestTopic(ctx context.Context, in *SubscribeRequestMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnsubscribeRequestTopic(ctx context.Context, in *UnsubscribeRequestMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	EventTopic(ctx context.Context, in *EventMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type coreClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreClient(cc grpc.ClientConnInterface) CoreClient {
	return &coreClient{cc}
}

func (c *coreClient) SubscribeRequestTopic(ctx context.Context, in *SubscribeRequestMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/control.core.v1.Core/SubscribeRequestTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) UnsubscribeRequestTopic(ctx context.Context, in *UnsubscribeRequestMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/control.core.v1.Core/UnsubscribeRequestTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) EventTopic(ctx context.Context, in *EventMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/control.core.v1.Core/EventTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServer is the server API for Core service.
// All implementations must embed UnimplementedCoreServer
// for forward compatibility
type CoreServer interface {
	SubscribeRequestTopic(context.Context, *SubscribeRequestMessage) (*emptypb.Empty, error)
	UnsubscribeRequestTopic(context.Context, *UnsubscribeRequestMessage) (*emptypb.Empty, error)
	EventTopic(context.Context, *EventMessage) (*emptypb.Empty, error)
	mustEmbedUnimplementedCoreServer()
}

// UnimplementedCoreServer must be embedded to have forward compatible implementations.
type UnimplementedCoreServer struct {
}

func (UnimplementedCoreServer) SubscribeRequestTopic(context.Context, *SubscribeRequestMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscribeRequestTopic not implemented")
}
func (UnimplementedCoreServer) UnsubscribeRequestTopic(context.Context, *UnsubscribeRequestMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnsubscribeRequestTopic not implemented")
}
func (UnimplementedCoreServer) EventTopic(context.Context, *EventMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EventTopic not implemented")
}
func (UnimplementedCoreServer) mustEmbedUnimplementedCoreServer() {}

// UnsafeCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServer will
// result in compilation errors.
type UnsafeCoreServer interface {
	mustEmbedUnimplementedCoreServer()
}

func RegisterCoreServer(s grpc.ServiceRegistrar, srv CoreServer) {
	s.RegisterService(&Core_ServiceDesc, srv)
}

func _Core_SubscribeRequestTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).SubscribeRequestTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.core.v1.Core/SubscribeRequestTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).SubscribeRequestTopic(ctx, req.(*SubscribeRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_UnsubscribeRequestTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).UnsubscribeRequestTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.core.v1.Core/UnsubscribeRequestTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).UnsubscribeRequestTopic(ctx, req.(*UnsubscribeRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_EventTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).EventTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.core.v1.Core/EventTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).EventTopic(ctx, req.(*EventMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Core_ServiceDesc is the grpc.ServiceDesc for Core service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Core_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.core.v1.Core",
	HandlerType: (*CoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubscribeRequestTopic",
			Handler:    _Core_SubscribeRequestTopic_Handler,
		},
		{
			MethodName: "UnsubscribeRequestTopic",
			Handler:    _Core_UnsubscribeRequestTopic_Handler,
		},
		{
			MethodName: "EventTopic",
			Handler:    _Core_EventTopic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control/core/v1/core.proto",
}
